name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Find new folder
      id: newfolder
      run: |
        git fetch --depth=2
        # Get the commit hashes
        PREV_COMMIT=$(git rev-parse HEAD~1)
        NEW_COMMIT=$(git rev-parse HEAD)
        echo "Previous commit: $PREV_COMMIT"
        echo "New commit: $NEW_COMMIT"
        
        # Find new or modified folders with requirements.txt and streamlit.py
        NEW_FOLDER=$(git diff --name-only $PREV_COMMIT $NEW_COMMIT | grep -E '^[^/]+/requirements.txt' | cut -d'/' -f1 | sort -u | head -n 1)
        if [ -z "$NEW_FOLDER" ]; then
          echo "No new folder detected. Exiting."
          exit 1
        fi
        NEW_FOLDER=$(echo "$NEW_FOLDER" | sed 's:/*$::')
        APP_NAME=${NEW_FOLDER//[^a-zA-Z0-9]/-}-${GITHUB_SHA::8}
        echo "NEW_FOLDER=${NEW_FOLDER}" >> $GITHUB_ENV
        echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
      shell: bash

    - name: Debug new folder and app name
      run: |
        echo "New folder is: ${{ env.NEW_FOLDER }}"
        echo "App name is: ${{ env.APP_NAME }}"
      shell: bash

    - name: Set up Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Create Heroku App
      run: |
        heroku create ${{ env.APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Deploy to Heroku
      run: |
        cd ${{ env.NEW_FOLDER }}
        git init
        git remote add heroku https://git.heroku.com/${{ env.APP_NAME }}.git
        git add .
        git commit -m "Deploy to Heroku"
        git push heroku master --force
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Get Heroku App URL
      run: |
        APP_URL=$(heroku apps:info -a ${{ env.APP_NAME }} | grep "Web URL" | awk '{print $3}')
        echo "HEROKU_APP_URL=${APP_URL}" >> $GITHUB_ENV
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Print Heroku App URL
      run: echo "The Heroku app is deployed at:${{ env.HEROKU_APP_URL }}"
      shell: bash
