name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Scan for new folders and set up environment variables
      id: scan_new_folders
      run: |
        echo "Scanning for new folders..."
        NEW_FOLDERS=$(find . -name 'requirements.txt' -exec dirname {} \;)
        if [ -z "$NEW_FOLDERS" ]; then
          echo "No new folders found. Exiting."
          exit 1
        fi
        echo "NEW_FOLDERS=${NEW_FOLDERS}" >> $GITHUB_ENV
        echo "Found new folders: $NEW_FOLDERS"

    - name: Set up Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Deploy to Heroku
      run: |
        for FOLDER in ${{ env.NEW_FOLDERS }}; do
          APP_NAME=$(basename $FOLDER)-${GITHUB_SHA::8}
          echo "Deploying folder $FOLDER to Heroku app $APP_NAME"
          cd $FOLDER
          git init
          heroku create $APP_NAME
          git remote add heroku https://git.heroku.com/$APP_NAME.git
          git add .
          git commit -m "Deploy to Heroku"
          git push heroku master --force
          cd ..
          APP_URL=$(heroku apps:info -a $APP_NAME | grep "Web URL" | awk '{print $3}')
          echo "The Heroku app is deployed at: $APP_URL"
        done
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
