name: Deploy to AWS Elastic Beanstalk

on:
  push:
    paths:
      - '**/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Ensure we fetch enough history to access HEAD^

    - name: Find new folder
      id: newfolder
      run: |
        git fetch --depth=2
        NEW_FOLDER=$(git diff --name-only HEAD^ HEAD | grep -oE '^[^/]+/' | sort -u | head -n 1)
        echo "NEW_FOLDER=${NEW_FOLDER}" >> $GITHUB_ENV
      shell: bash

    - name: Debug new folder
      run: echo "New folder is:${{ env.NEW_FOLDER }}"
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        cd ${{ env.NEW_FOLDER }}
        ls -al
        if [ -f requirements.txt ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        else
          echo "No requirements.txt found in the new folder."
          exit 1
        fi
      shell: bash

    - name: Run setup script
      run: |
        cd ${{ env.NEW_FOLDER }}
        if [ -f setup.py ]; then
          python setup.py install
        else
          echo "No setup.py found in the new folder."
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      shell: bash

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        cd ${{ env.NEW_FOLDER }}
        eb init -p python-3.7 my-app --region ${{ secrets.AWS_REGION }}
        eb create ${{ env.NEW_FOLDER }}-env
        eb deploy ${{ env.NEW_FOLDER }}-env
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      shell: bash

    - name: Get deployed app URL
      id: get-url
      run: |
        ENV_URL=$(aws elasticbeanstalk describe-environments --environment-names ${{ env.NEW_FOLDER }}-env --query 'Environments[0].CNAME' --output text --region ${{ secrets.AWS_REGION }})
        echo "ENV_URL=http://$ENV_URL" >> $GITHUB_ENV
      shell: bash

    - name: Print URL
      run: echo "The Streamlit app is deployed at:${{ env.ENV_URL }}"
      shell: bash
