name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Run setup script
      id: setup
      run: python setup.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}

    - name: Get deployed app URL
      id: get-url
      run: |
        IDENTIFIER=$(git log -1 --pretty=%B | grep -oP '(?<=Add directory for ).*')
        ENV_URL=$(python -c "import boto3; client = boto3.client('elasticbeanstalk', region_name='${{ secrets.AWS_REGION }}'); environments = client.describe_environments(EnvironmentNames=['${IDENTIFIER}-env'])['Environments']; print(environments[0]['CNAME']) if environments else ''")
        echo "ENV_URL=http://$ENV_URL" >> $GITHUB_ENV

    - name: Print URL
      run: echo "The Streamlit app is deployed at: ${{ env.ENV_URL }}"
